workflows:
  ios-release-workflow:
    name: Build iOS App
    max_build_duration: 45
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean and Get Dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Set iOS Deployment Target
        script: |
          echo "Updating iOS deployment target to 13.0"
          sed -i '' 's/platform :ios, .*/platform :ios, '\''13.0'\''/' ios/Podfile
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Build iOS
        script: |
          flutter build ios --release
    artifacts:
      - build/ios/iphoneos/Runner.app
