# ios/Podfile
platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_installation
  # Use the generated Podfile from Flutter
  flutter_application_path = File.expand_path('..')
  load File.join(flutter_application_path, '.flutter-plugins-dependencies')
  system('flutter', 'pub', 'get')
  system('flutter', 'packages', 'pub', 'run', 'build_runner', 'build', '--delete-conflicting-outputs')
end

install! 'cocoapods', :disable_input_output_paths => true

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
